module.exports = {
	MESSAGE_RECEIVE: "MESSAGE_RECEIVE",
	MESSAGE_SEND: "MESSAGE_SEND",
	ROOM_RECEIVE: "ROOM_RECEIVE",
	ROOM_SET: "ROOM_SET",
	SOCKET_CONNECT: "connect",
	USERNAME_SET: "USERNAME_SET"
}
